[tox]
env_list = py38, py311, py312
skip_missing_interpreters = true

[testenv]
skip_install = true
deps = -r requirements-dev.txt
commands = pytest {posargs}

[pytest]
pythonpath = src/plugin
testpaths = tests

[testenv:screenshots]
base_python = python3.12
deps = flow-render @ git+https://github.com/Garulf/flow-render@v0.14.3
commands_pre = playwright install chromium
commands = python scripts/screenshots.py

[testenv:readme]
deps = readwright==0.5.0
commands = readwright render
