name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags-ignore:
      - "v*"
    paths-ignore:
      - .github/workflows/*
      - README.md
      - assets/*
env:
  PYTHON_VER: "3.10"
jobs:
  deps:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Cache plugin dependencies
        id: plugin-cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ env.PYTHON_VER }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache Build dependencies
        id: build-cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ env.PYTHON_VER }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Plugin dependencies
        if: steps.plugin-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt
      - name: Install Build dependencies
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          pip install -r ./requirements-dev.txt
      - name: Build
        run: |
          python ./scripts/build.py
          python ./scripts/package.py
      - name: Get Plugin's version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "./src/plugin.json"
          prop_path: "Version"
      - name: Get Plugin Name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "./src/plugin.json"
          prop_path: "Name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: "./staging/${{steps.name.outputs.prop}}.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
